name: sero
description: "Speak without the restriction of SMS."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.11.0-93.1.beta

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^17.0.0
  flutter_bloc: ^9.1.1
  flutter_secure_storage: ^9.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/icons
    - assets/fonts
  fonts:
    - family: Geist
      fonts:
        - asset: assets/fonts/Geist.ttf
          weight: 700