name: sero
description: "Speak without the restriction of SMS."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.11.0-93.1.beta

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^17.0.0
  flutter_bloc: ^9.1.1
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.2.3
  flutter_otp_text_field: ^1.5.1+1
  flutter_dotenv: ^6.0.0
  vector_graphics: ^1.1.19
  intl_phone_field: ^3.2.0
  graphql_flutter: ^5.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  connectivity_plus: ^6.1.3
  cached_network_image: ^3.4.1
  image_picker: ^1.2.1
  cryptography: ^2.9.0
  http: ^1.6.0
  http_parser: ^4.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  vector_graphics_compiler: ^1.1.19
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7
  flutter_lints: ^6.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13
flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/vectors/
  fonts:
    - family: Geist
      fonts:
        - asset: assets/fonts/Geist.ttf
          weight: 700